<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>GitHub Dashboard</title>
    <link rel="stylesheet" href="styles.css">
</head>

<body>
    <header>
        <h1>GitHub Dashboard</h1>
    </header>

    <section id="charts">
        <div class="chart-container">
            <h2>Commits Over Time</h2>
            <canvas id="commitsChart"></canvas>
        </div>

        <div class="chart-container">
            <h2>Repository Languages</h2>
            <canvas id="languagesChart"></canvas>
        </div>
    </section>

    <section id="issues">
        <h2>Open Issues</h2>
        <ul id="issueList">
            <!-- Issues will be dynamically added here -->
        </ul>
    </section>

    <footer>
        <p>&copy; 2023 GitHub Dashboard</p>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="app.js"></script>
</body>

</html>
